# Site settings
title: Federation Playbook
name: Federation Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: Federation Guidance
highlighter: rouge
repo_url: https://github.com/GSA/ficam-federation
baseurl: '/ficam-federation'
branch: federalist-pages
# Federalist overwrites the site.branch value when deploying
# the site.branch was used in dynamic link generation for objects like Edit Page
# we want the dynamic links to send users to the staging branch.  Adding new site variable to ensure federalist doesn't overwrite.

# Links
# List links that you would like to appear on the top navigation bar here
navbar:
- title: IDmanagement.gov
  description: Idmanagement.gov
  url: https://www.idmanagement.gov
- title: Federal ICAM Architecture
  description: Federal ICAM Architecture
  url: https://arch.idmanagement.gov
- title: PIV Guides
  description: PIV Guides
  url: https://piv.idmanagement.gov
- title: Federal PKI Guides
  description: Federal PKI Guides
  url: https://fpki.idmanagement.gov


# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Introduction
  url: ''
  internal: true
  coll: false
- text: Establish Federation Governance
  url: 1_step-1
  internal: true
  coll: false
- text: Identify Business Considerations
  url: 2_step-2
  internal: true
  coll: false
- text: Understand the RP Environment
  url: 3_step-3
  internal: true
  coll: false
- text: Determine Applicability to Security and Privacy Controls
  url: 4_step-4
  internal: true
  coll: false
- text: Determine Acceptable Credentials
  url: 5_step-5
  internal: true
  coll: false
- text: Partner with an Identity Provider(s)
  url: 6_step-6
  internal: true
  coll: false
- text: Evaluate Existing Infrastructure 
  url: 7_step-7
  internal: true
  coll: false
- text: Evaluate Optimal Solution Architecture
  url: 8_step-8
  internal: true
  coll: false
- text: Integrate with CSP
  url: 9_step-9
  internal: true
  coll: false
- text: Create and Manage User Accounts
  url: 10_step-10
  internal: true
  coll: false
- text: Account Management
  url: 11_step-11
  internal: true
  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false
include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
