# Site settings
title: Federation Playbook
name: Federation Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: Federation Guidance
baseurl: '/federation'
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lachellel
highlighter: rouge
branch: master

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /federation/img/logo.png
logoalt: Federal Identity Credential and Access Management

ficam_playbooks_url: /ficam-guides/

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: federation
  description: FICAM Playbook - Federation Guidance
  url: https://github.com/gsa/federation

# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Home
  url: index.html
  internal: true
  coll: false
- text: Overview of Federation
  url: overview/index/
  internal: true
  coll: true
  collname: overview
- text: Plan Your Federation
  url: plan/index
  internal: true
  coll: true
  collname: plan
- text: Design Your Federation
  url: design/index
  internal: true
  coll: true
  collname: design
- text: Implement Your Federation
  url: implement/index/
  internal: true
  coll: true
  collname: implement
- text: Contribute
  url: contribute
  internal: true
  coll: false
  
collections:
  overview: 
    label: "Overview"
    permalink: /overview/:path/
    output: true
  plan:
    label: "Plan"
    permalink: /plan/:path/
    output: true
  design:
    label: "Design"
    permalink: /design/:path/
    output: true
  implement:
    label: "Implement"
    permalink: /implement/:path/
    output: true
include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
