# Site settings
title: Federation Playbook
name: Federation Playbook
email: icam@gsa.gov
author:
    name: FICAM
description: Federation Guidance
baseurl: '/ficam-federation'
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lachellel
highlighter: rouge
branch: master

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /ficam-federation/img/logo.png
logoalt: Federal Identity Credential and Access Management

ficam_playbooks_url: /ficam-guides/

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: federation
  description: FICAM Playbook - Federation Guidance
  url: https://github.com/gsa/ficam-federation

# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Home
  url: index.html
  internal: true
  coll: false
- text: Step 1 - Establish Federation Governance
  url: 1_step-1
  internal: true
  coll: false
- text: Step 2 - Identify Business Considerations
  url: 2_step-2
  internal: true
  coll: false
- text: Step 3 - Understand the RP Environment
  url: 3_step-3
  internal: true
  coll: false
- text: Step 4 - Determine Applicability to Security and Privacy Controls
  url: 4_step-4
  internal: true
  coll: false
- text: Step 5 - Determine Acceptable Credentials
  url: 5_step-5
  internal: true
  coll: false
- text: Step 6 - Partner with an Identity Provider(s)
  url: 6_step-6
  internal: true
  coll: false
- text: Step 7 - Evaluate Existing Infrastructure 
  url: 7_step-7
  internal: true
  coll: false
- text: Step 8 - Evaluate Optimal Solution Architecture
  url: 8_step-8
  internal: true
  coll: false
- text: Step 9 - Integrate with CSP
  url: 9_step-9
  internal: true
  coll: false
- text: Step 10 - Create and Manage User Accounts
  url: 10_step-10
  internal: true
  coll: false
- text: Step 11 - Create and Manage User Accounts
  url: 11_step-11
  internal: true
  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false
include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
